// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("Morphir.Core")>]
[<assembly: AssemblyProductAttribute("Morphir")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2023-05-23T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "Alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "73eab6e38259143389e5ec1421422fae74d130a8")>]
do ()

module internal AssemblyVersionInformation =
  [<Literal>]
  let AssemblyTitle = "Morphir.Core"

  [<Literal>]
  let AssemblyProduct = "Morphir"

  [<Literal>]
  let AssemblyVersion = "0.1.0"

  [<Literal>]
  let AssemblyMetadata_ReleaseDate = "2023-05-23T00:00:00.0000000+00:00"

  [<Literal>]
  let AssemblyFileVersion = "0.1.0"

  [<Literal>]
  let AssemblyInformationalVersion = "0.1.0"

  [<Literal>]
  let AssemblyMetadata_ReleaseChannel = "Alpha"

  [<Literal>]
  let AssemblyMetadata_GitHash = "73eab6e38259143389e5ec1421422fae74d130a8"
