package morphir-ir:name@0.0.1;

interface name {
    variant run{run(string)}

    variant name {        
        name(list<run>)
    }

    from-string: func(input:string) -> name;
    to-string: func(name:name) ->  string;
}

world morphir-ir-name {
    export name;
}

world app {
    import name;
}